"""
Django settings for tfn_ctv project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dotenv
from dotenv import load_dotenv

# Load environment variables from .env file
try:
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Get SECRET_KEY from environment variable or use default for development
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-yu!84b5rz0^s6uz96@0tq^r)7eoz#o&&@)u+dnzqti0%24$+_g')

# SECURITY WARNING: don't run with debug turned on in production!
# Get DEBUG from environment variable (default to True for development)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Set ALLOWED_HOSTS based on environment
# In production, this should be a comma-separated list of domains
# For development, we allow localhost and 127.0.0.1
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'music_beta',
    'artist_portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'tfn_ctv.rate_limiting.RateLimitMiddleware',
]

ROOT_URLCONF = 'tfn_ctv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.static',
                # 'sekizai.context_processors.sekizai',

            ],
        },
    },
]

WSGI_APPLICATION = 'tfn_ctv.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ['username', 'email', 'first_name', 'last_name'],
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'tfn_ctv.password_validation.ComplexityValidator',
        'OPTIONS': {
            'min_upper': 1,
            'min_lower': 1,
            'min_digits': 1,
            'min_special': 1,
        }
    },
]

# Password policy settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours in seconds
PASSWORD_EXPIRY_DAYS = 90  # Password expires after 90 days
PASSWORD_HISTORY_COUNT = 5  # Remember last 5 passwords to prevent reuse

# Security settings for cookies and HTTPS
# These settings are only applied when DEBUG is False (production)
if not DEBUG:
    # Secure cookie settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Django CMS language settings
LANGUAGES = [
    ('en', 'English'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploads)
# Use Amazon S3 when AWS_STORAGE_BUCKET_NAME is set; otherwise local filesystem.
# See: https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html
MEDIA_ROOT = BASE_DIR / 'media'
USE_S3 = bool(os.environ.get('AWS_STORAGE_BUCKET_NAME'))
if USE_S3:
    _s3_bucket = os.environ['AWS_STORAGE_BUCKET_NAME']
    _s3_region = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    _s3_domain = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or f'{_s3_bucket}.s3.{_s3_region}.amazonaws.com'
    MEDIA_URL = f'https://{_s3_domain}/media/'
else:
    MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User model
AUTH_USER_MODEL = 'music_beta.User'

# Email settings
DEVELOPER_EMAIL = os.environ.get('DEVELOPER_EMAIL', 'developer@tfnms.co')
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@tfnms.co'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_USE_TLS = True
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@tfnms.co')

# Audius (Sandcastle) API – for artist/streaming integrations. Set in .env as AUDIUS_API_KEY.
# See https://audius.org/ and Audius API docs. Do not commit the key.
AUDIUS_API_KEY = os.environ.get('AUDIUS_API_KEY', '').strip() or None

# Default storage: S3 for media when configured, else local.
# Credentials: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY (or IAM role when on AWS).
if USE_S3:
    _bucket = os.environ['AWS_STORAGE_BUCKET_NAME']
    _region = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    S3_DEFAULT_OPTIONS = {
        'bucket_name': _bucket,
        'region_name': _region,
        'location': 'media',
        'file_overwrite': False,
        'default_acl': os.environ.get('AWS_DEFAULT_ACL', 'public-read'),
        'object_parameters': {'CacheControl': 'max-age=86400'},
        'custom_domain': os.environ.get('AWS_S3_CUSTOM_DOMAIN') or f'{_bucket}.s3.{_region}.amazonaws.com',
        'querystring_auth': False,
    }
else:
    S3_DEFAULT_OPTIONS = {}

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': S3_DEFAULT_OPTIONS,
    } if USE_S3 else {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'LOCATION': BASE_DIR / 'media',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        'LOCATION': BASE_DIR / 'static',
    },
}

