# Generated by Django 5.2.1 on 2025-05-12 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the artist name', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Enter a brief bio of the artist', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a music genre (e.g. Rock, Jazz, Hip Hop)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the album title', max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.CharField(default='https://via.placeholder.com/300', help_text='URL to album cover image', max_length=500)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_beta.artist')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this album', to='music_beta.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the track title', max_length=200)),
                ('audio_file', models.CharField(default='https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', help_text='URL to audio file', max_length=500)),
                ('duration', models.CharField(blank=True, help_text='Duration of the track (e.g. 3:45)', max_length=10)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_beta.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_beta.artist')),
            ],
        ),
    ]
