# Generated by Django 5.2.1 on 2025-05-13 01:07

import music_beta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_beta', '0003_remove_adcampaign_video_url_adcampaign_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (preferred)', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='bitrate',
            field=models.IntegerField(blank=True, help_text='Bitrate in kbps', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='composer',
            field=models.CharField(blank=True, help_text='Composer from ID3 tag', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='genre_tag',
            field=models.CharField(blank=True, help_text='Genre from ID3 tag', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='last_played',
            field=models.DateTimeField(blank=True, help_text='When the track was last played', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0, help_text='Number of times the track has been played'),
        ),
        migrations.AddField(
            model_name='track',
            name='sample_rate',
            field=models.IntegerField(blank=True, help_text='Sample rate in Hz', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.CharField(blank=True, help_text='Track number from ID3 tag', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='year',
            field=models.CharField(blank=True, help_text='Year of release', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_to_privacy',
            field=models.BooleanField(default=False, help_text='User has agreed to Privacy Policy'),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, help_text='User has agreed to Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='user',
            name='agreement_date',
            field=models.DateTimeField(blank=True, help_text='When the user agreed to terms', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_marketing',
            field=models.BooleanField(default=False, help_text='User has opted in to marketing emails'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='video',
            field=models.FileField(blank=True, help_text='Video file (max 50MB)', null=True, upload_to=music_beta.models.ad_video_path),
        ),
    ]
