# Generated by Django 5.2.1 on 2025-05-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_beta', '0004_adcampaign_youtube_url_track_bitrate_track_composer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaign',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL (preferred)', null=True),
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(help_text='Name of copyright holder', max_length=200)),
                ('license_type', models.CharField(help_text='License type (e.g. Creative Commons)', max_length=200)),
                ('license_url', models.URLField(blank=True, help_text='Link to the license or terms', null=True)),
                ('credits', models.TextField(blank=True, help_text='Credits/notes related to authorship, contributors, etc.', null=True)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Copyright or License Year', null=True)),
                ('document', models.FileField(blank=True, help_text='Upload copyright/license document PDF', null=True, upload_to='copyright_docs/')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyrights', to='music_beta.album')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyrights', to='music_beta.track')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='copyright',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music_beta.copyright'),
        ),
        migrations.AddField(
            model_name='track',
            name='copyright',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music_beta.copyright'),
        ),
    ]
