# Generated by Django 6.0.2 on 2026-02-17 03:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import music_beta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('music_beta', '0006_user_is_active_user_last_login_user_user_type_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Friday date for this Song of the Week')),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('song', models.CharField(blank=True, max_length=300)),
                ('youtube_url', models.URLField(blank=True, help_text='Song / video link')),
                ('spotify_artist_url', models.URLField(blank=True)),
                ('apple_music_artist_url', models.URLField(blank=True)),
                ('instagram_artist_url', models.URLField(blank=True)),
                ('about_artist', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Track description if available')),
            ],
            options={
                'verbose_name': 'Song of the Week',
                'verbose_name_plural': 'Songs of the Week',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='bpm',
            field=models.FloatField(blank=True, help_text='Beats per minute', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='key',
            field=models.CharField(blank=True, help_text='Musical key (e.g. C major, A minor)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='mood',
            field=models.CharField(blank=True, help_text='Mood/emotion from DEAM dataset', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='video',
            field=models.FileField(blank=True, help_text='Video file', null=True, upload_to=music_beta.models.ad_video_path),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='holder',
            field=models.CharField(default='TFN Music', help_text='Name of copyright holder (always our organization)', max_length=200),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='Copyright or License Year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
