# Generated by Django 5.2.1 on 2025-05-19 16:25

import artist_portal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_beta', '0006_user_is_active_user_last_login_user_user_type_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to=artist_portal.models.artist_profile_image_path)),
                ('bio', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('soundcloud', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('featured_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_on_profiles', to='music_beta.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to='music_beta.user')),
            ],
        ),
    ]
