# Generated by Django 6.0.2 on 2026-02-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='apple_music',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ArtistStreamingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_data', models.JSONField(blank=True, null=True)),
                ('spotify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('apple_music_data', models.JSONField(blank=True, null=True)),
                ('apple_music_updated_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_data', to='artist_portal.artistprofile')),
            ],
        ),
    ]
